{
 "title": "Topology Overview",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "protocol",
    "label": "Protocol",
    "query": "label_values(proxy_build_info, ort_protocol)"
   }
  ]
 },
 "panels": [
  { "title": "Load: $protocol", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "protocol" },
  {
   "title": "RPS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(response_latency_seconds_count{ort_role=\"load\",ort_protocol=\"$protocol\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(response_latency_ms_count{ort_role=\"load\",ort_protocol=\"$protocol\",direction=\"outbound\"}[$__rate_interval])) by (pod, dst_pod)",
     "legendFormat": "responses from {{pod}} "
    }
   ]
  },
  {
   "title": "Response Latencies",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(response_latency_seconds{ort_role=\"load\",ort_protocol=\"$protocol\",quantile!=\"1\"}) by (quantile, pod)",
     "legendFormat": "{{quantile}} {{pod}}"
    }
   ]
  },
  {
   "title": "Proxy Latencies",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(response_latency_ms_bucket{ort_role=\"load\",ort_protocol=\"$protocol\",direction=\"outbound\"}[$__rate_interval])) by (le, pod, dst_pod))",
     "legendFormat": "0.5 {{pod}} from {{dst_pod}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(response_latency_ms_bucket{ort_role=\"load\",ort_protocol=\"$protocol\",direction=\"outbound\"}[$__rate_interval])) by (le, pod, dst_pod))",
     "legendFormat": "0.9 {{pod}} from {{dst_pod}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(response_latency_ms_bucket{ort_role=\"load\",ort_protocol=\"$protocol\",direction=\"outbound\"}[$__rate_interval])) by (le, pod, dst_pod))",
     "legendFormat": "0.99 {{pod}} from {{dst_pod}}"
    }
   ]
  },
  {
   "title": "Proxy CPU",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{ort_role=\"load\",ort_protocol=\"$protocol\",job=\"proxy\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Proxy RSS",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{ort_role=\"load\",ort_protocol=\"$protocol\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "TCP Connects",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tcp_open_total{direction=\"outbound\",ort_role=\"load\",ort_protocol=\"$protocol\",peer=\"dst\"}[$__rate_interval])) by (pod, dst_pod)",
     "legendFormat": "connect {{pod}} to {{dst_pod}}"
    },
    {
     "expr": "sum(rate(tcp_open_total{direction=\"outbound\",ort_role=\"load\",ort_protocol=\"$protocol\",peer=\"src\"}[$__rate_interval])) by (pod)",
     "legendFormat": "connect {{pod}} local"
    },
    {
     "expr": "sum(rate(tcp_close_total{direction=\"outbound\",ort_role=\"load\",ort_protocol=\"$protocol\",peer=\"dst\"}[$__rate_interval])) by (pod, dst_pod)",
     "legendFormat": "close {{pod}} from {{dst_pod}}"
    },
    {
     "expr": "sum(rate(tcp_close_total{direction=\"outbound\",ort_role=\"load\",ort_protocol=\"$protocol\",peer=\"src\"}[$__rate_interval])) by (pod)",
     "legendFormat": "close {{pod}} local"
    }
   ]
  },
  {
   "title": "TCP Connections",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(tcp_open_connections{direction=\"outbound\",ort_role=\"load\",ort_protocol=\"$protocol\",peer=\"src\"}) by (pod)",
     "legendFormat": "{{pod}} local"
    },
    {
     "expr": "sum(tcp_open_connections{direction=\"outbound\",ort_role=\"load\",ort_protocol=\"$protocol\",peer=\"dst\"}) by (pod, dst_pod)",
     "legendFormat": "{{pod}} to {{dst_pod}}"
    }
   ]
  },
  { "title": "Load: $protocol", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "RPS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(response_latency_seconds_count{ort_role=\"load\",ort_protocol=\"$protocol\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(response_latency_ms_count{ort_role=\"load\",ort_protocol=\"$protocol\",direction=\"outbound\"}[$__rate_interval])) by (pod, dst_pod)",
     "legendFormat": "responses from {{pod}} "
    }
   ]
  },
  {
   "title": "Response Latencies",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(response_latency_seconds{ort_role=\"load\",ort_protocol=\"$protocol\",quantile!=\"1\"}) by (quantile, pod)",
     "legendFormat": "{{quantile}} {{pod}}"
    }
   ]
  },
  {
   "title": "Proxy Latencies",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(response_latency_ms_bucket{ort_role=\"load\",ort_protocol=\"$protocol\",direction=\"outbound\"}[$__rate_interval])) by (le, pod, dst_pod))",
     "legendFormat": "0.5 {{pod}} from {{dst_pod}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(response_latency_ms_bucket{ort_role=\"load\",ort_protocol=\"$protocol\",direction=\"outbound\"}[$__rate_interval])) by (le, pod, dst_pod))",
     "legendFormat": "0.9 {{pod}} from {{dst_pod}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(response_latency_ms_bucket{ort_role=\"load\",ort_protocol=\"$protocol\",direction=\"outbound\"}[$__rate_interval])) by (le, pod, dst_pod))",
     "legendFormat": "0.99 {{pod}} from {{dst_pod}}"
    }
   ]
  },
  {
   "title": "Proxy CPU",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{ort_role=\"load\",ort_protocol=\"$protocol\",job=\"proxy\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Proxy RSS",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{ort_role=\"load\",ort_protocol=\"$protocol\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "TCP Connects",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tcp_open_total{direction=\"outbound\",ort_role=\"load\",ort_protocol=\"$protocol\",peer=\"dst\"}[$__rate_interval])) by (pod, dst_pod)",
     "legendFormat": "connect {{pod}} to {{dst_pod}}"
    },
    {
     "expr": "sum(rate(tcp_open_total{direction=\"outbound\",ort_role=\"load\",ort_protocol=\"$protocol\",peer=\"src\"}[$__rate_interval])) by (pod)",
     "legendFormat": "connect {{pod}} local"
    },
    {
     "expr": "sum(rate(tcp_close_total{direction=\"outbound\",ort_role=\"load\",ort_protocol=\"$protocol\",peer=\"dst\"}[$__rate_interval])) by (pod, dst_pod)",
     "legendFormat": "close {{pod}} from {{dst_pod}}"
    },
    {
     "expr": "sum(rate(tcp_close_total{direction=\"outbound\",ort_role=\"load\",ort_protocol=\"$protocol\",peer=\"src\"}[$__rate_interval])) by (pod)",
     "legendFormat": "close {{pod}} local"
    }
   ]
  },
  {
   "title": "TCP Connections",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(tcp_open_connections{direction=\"outbound\",ort_role=\"load\",ort_protocol=\"$protocol\",peer=\"src\"}) by (pod)",
     "legendFormat": "{{pod}} local"
    },
    {
     "expr": "sum(tcp_open_connections{direction=\"outbound\",ort_role=\"load\",ort_protocol=\"$protocol\",peer=\"dst\"}) by (pod, dst_pod)",
     "legendFormat": "{{pod}} to {{dst_pod}}"
    }
   ]
  },
  { "title": "Servers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Total RPS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(response_latency_ms_count{ort_role=\"server\"}[$__rate_interval]))",
     "legendFormat": "{{status_code}} {{pod}} from {{client_id}}"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(response_latency_ms_count{ort_role=\"server\"}[$__rate_interval])) by (status_code, pod, client_id)",
     "legendFormat": "{{status_code}} {{pod}} from {{client_id}}"
    }
   ]
  },
  {
   "title": "Proxy CPU",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{ort_role=\"server\"}[$__rate_interval])",
     "legendFormat": "{{status_code}} {{pod}} {{client_id}}"
    }
   ]
  },
  {
   "title": "Proxy RSS",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{ort_role=\"server\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "TCP Connects",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tcp_open_total{direction=\"inbound\",ort_role=\"server\",peer=\"src\"}[$__rate_interval])) by (pod, client_id)",
     "legendFormat": "connect {{pod}} from {{client_id}}"
    },
    {
     "expr": "sum(rate(tcp_open_total{direction=\"inbound\",ort_role=\"server\",peer=\"dst\"}[$__rate_interval])) by (pod)",
     "legendFormat": "connect {{pod}} local"
    },
    {
     "expr": "sum(rate(tcp_close_total{direction=\"inbound\",ort_role=\"server\",peer=\"src\"}[$__rate_interval])) by (pod, client_id)",
     "legendFormat": "close {{pod}} from {{client_id}}"
    },
    {
     "expr": "sum(rate(tcp_close_total{direction=\"inbound\",ort_role=\"server\",peer=\"dst\"}[$__rate_interval])) by (pod)",
     "legendFormat": "close {{pod}} local"
    }
   ]
  },
  {
   "title": "TCP Connections",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(tcp_open_connections{direction=\"inbound\",ort_role=\"server\",peer=\"src\"}) by (pod, client_id)",
     "legendFormat": "{{pod}} from {{client_id}}"
    },
    {
     "expr": "sum(tcp_open_connections{direction=\"inbound\",ort_role=\"server\",peer=\"dst\"}) by (pod)",
     "legendFormat": "{{pod}} local"
    }
   ]
  }
 ]
}