{{- define "ort.linkerd" }}
linkerd.io/inject: {{ .inject | default "enabled" }}
{{-   range $k, $v := .config }}
{{-     if $v }}
config.linkerd.io/{{ kebabcase $k }}: {{ quote $v }}
{{-     end }}
{{-   end }}
{{- end -}}
