{
 "title": "Ort",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "protocol",
    "label": "Protocol",
    "query": "label_values(proxy_build_info, ort_protocol)"
   }
  ]
 },
 "panels": [
  { "title": "Load: $protocol", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "protocol" },
  {
   "title": "RPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(response_latency_ms_count{ort_role=\"load\",ort_protocol=\"$protocol\",direction=\"outbound\"}[$__rate_interval])) by (pod, dst_pod)",
     "legendFormat": "{{pod}} to {{dst_pod}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(response_latency_ms_bucket{ort_role=\"load\",ort_protocol=\"$protocol\",direction=\"outbound\"}[$__rate_interval])) by (le)) / 1000",
     "legendFormat": "Proxy p50"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(response_latency_ms_bucket{ort_role=\"load\",ort_protocol=\"$protocol\",direction=\"outbound\"}[$__rate_interval])) by (le)) / 1000",
     "legendFormat": "Proxy p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(response_latency_ms_bucket{ort_role=\"load\",ort_protocol=\"$protocol\",direction=\"outbound\"}[$__rate_interval])) by (le)) / 1000",
     "legendFormat": "Proxy p99"
    },
    {
     "expr": "sum(response_latency_seconds{ort_role=\"load\",ort_protocol=\"$protocol\",quantile!=\"1\",quantile!=\"0\"}) by (quantile)",
     "legendFormat": "Load {{quantile }}"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(response_latency_ms_bucket{ort_role=\"load\",ort_protocol=\"$protocol\",direction=\"outbound\"}[$__rate_interval])) by (le)) / 1000",
     "legendFormat": "Proxy p75"
    }
   ]
  },
  {
   "title": "Proxy CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{ort_role=\"load\",ort_protocol=\"$protocol\",job=\"proxy\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Proxy RSS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{ort_role=\"load\",ort_protocol=\"$protocol\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "TCP Connects",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(tcp_open_total{direction=\"outbound\",ort_role=\"load\",ort_protocol=\"$protocol\"}[$__rate_interval])) by (pod, peer)",
     "legendFormat": "connect {{pod}} {{peer}}"
    },
    {
     "expr": "-1*sum(delta(tcp_close_total{direction=\"outbound\",ort_role=\"load\",ort_protocol=\"$protocol\"}[$__rate_interval])) by (pod, peer)",
     "legendFormat": "close {{pod}} {{peer}}"
    }
   ]
  },
  {
   "title": "TCP Connections",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(tcp_open_connections{direction=\"outbound\",ort_role=\"load\",ort_protocol=\"$protocol\",peer=\"src\"}) by (pod)",
     "legendFormat": "{{pod}} local"
    },
    {
     "expr": "sum(tcp_open_connections{direction=\"outbound\",ort_role=\"load\",ort_protocol=\"$protocol\",peer=\"dst\"}) by (pod, dst_pod)",
     "legendFormat": "{{pod}} to {{dst_pod}}"
    }
   ]
  },
  {
   "title": "Stacks",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(stack_create_total{ort_role=\"load\",ort_protocol=\"$protocol\"}[$__rate_interval])) by (pod, direction, name)",
     "legendFormat": "new {{direction}} {{name}} {{pod}}"
    },
    {
     "expr": "sum(stack_create_total{ort_role=\"load\",ort_protocol=\"$protocol\"} - stack_drop_total{ort_role=\"load\",ort_protocol=\"$protocol\"}) by (pod, direction, name)",
     "legendFormat": "alive {{direction}} {{name}} {{pod}}"
    }
   ]
  },
  {
   "title": "Stack Polls",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(stack_poll_total_ms{ort_role=\"load\",ort_protocol=\"$protocol\"}[$__rate_interval])) by (pod, direction, name)",
     "legendFormat": "{{direction}} {{name}} {{pod}}"
    }
   ]
  },
  { "title": "Servers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "RPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(response_latency_ms_count{ort_role=\"server\"}[$__rate_interval])) by (pod, client_id)",
     "legendFormat": "{{pod}} from {{client_id}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(response_latency_ms_bucket{ort_role=\"server\",direction=\"inbound\"}[$__rate_interval])) by (le)) / 1000",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(response_latency_ms_bucket{ort_role=\"server\",direction=\"inbound\"}[$__rate_interval])) by (le)) / 1000",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(response_latency_ms_bucket{ort_role=\"server\",direction=\"inbound\"}[$__rate_interval])) by (le)) / 1000",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(response_latency_ms_bucket{ort_role=\"server\",direction=\"inbound\"}[$__rate_interval])) by (le)) / 1000",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Proxy CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{ort_role=\"server\"}[$__rate_interval])",
     "legendFormat": "{{status_code}} {{pod}} {{client_id}}"
    }
   ]
  },
  {
   "title": "Proxy RSS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{ort_role=\"server\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "TCP Connects",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(tcp_open_total{direction=\"inbound\",ort_role=\"server\",peer=\"src\"}[$__rate_interval])) by (pod, client_id)",
     "legendFormat": "connect {{pod}} from {{client_id}}"
    },
    {
     "expr": "sum(delta(tcp_open_total{direction=\"inbound\",ort_role=\"server\",peer=\"dst\"}[$__rate_interval])) by (pod)",
     "legendFormat": "connect {{pod}} local"
    },
    {
     "expr": "-1*sum(delta(tcp_close_total{direction=\"inbound\",ort_role=\"server\",peer=\"src\"}[$__rate_interval])) by (pod, client_id)",
     "legendFormat": "close {{pod}} from {{client_id}}"
    },
    {
     "expr": "-1*sum(delta(tcp_close_total{direction=\"inbound\",ort_role=\"server\",peer=\"dst\"}[$__rate_interval])) by (pod)",
     "legendFormat": "close {{pod}} local"
    }
   ]
  },
  {
   "title": "TCP Connections",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(tcp_open_connections{direction=\"inbound\",ort_role=\"server\"}) by (pod, client_id, peer, target_port)"
    }
   ]
  },
  {
   "title": "Stacks",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(stack_create_total{ort_role=\"server\"}[$__rate_interval])) by (pod, direction, name)",
     "legendFormat": "new {{direction}} {{name}} {{pod}}"
    },
    {
     "expr": "sum(stack_create_total{ort_role=\"server\"} - stack_drop_total{ort_role=\"server\"}) by (pod, direction, name)",
     "legendFormat": "alive {{direction}} {{name}} {{pod}}"
    }
   ]
  },
  {
   "title": "Stack Polls",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(stack_poll_total_ms{ort_role=\"server\"}[$__rate_interval])) by (pod, direction, name)",
     "legendFormat": "{{direction}} {{name}} {{pod}}"
    }
   ]
  }
 ]
}