{{- $ns := .Release.Namespace }}
{{- $img := .Values.image }}
{{- $replicas := int .Values.server.replicas }}
{{- $server := .Values.server }}
{{- $linkerd := deepCopy .Values.linkerd | merge $server.linkerd }}
{{- $protocols := .Values.protocols }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ort
  name: logical
  namespace: {{ $ns }}
spec:
  selector:
    app: ort
    ort.olix0r.net/role: server
  ports:
  {{- range $name, $proto := $protocols }}
  {{-   if $proto }}
    - port: {{ $proto.port }}
      targetPort: {{ $proto.port }}
      name: {{ $name }}
  {{-   end }}
  {{- end }}
{{- if $server.split }}
---
apiVersion: split.smi-spec.io/v1alpha1
kind: TrafficSplit
metadata:
  namespace: {{ $ns }}
  name: logical
spec:
  service: logical
  backends:
  {{- range $i, $e := until (int .Values.server.services) }}
    - service: concrete-{{ printf "%03d" $i }}
      weight: 1
  {{- end }}
{{- end }}
{{- range $i, $e := until (int .Values.server.services) }}
{{- if $server.split }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ort
  name: concrete-{{ printf "%03d" $i }}
  namespace: {{ $ns }}
spec:
  selector:
    app: ort
    ort.olix0r.net/role: server
    ort.olix0r.net/instance: {{ quote $i }}
  ports:
  {{- range $name, $proto := $protocols }}
  {{-   if $proto }}
    - port: {{ $proto.port }}
      targetPort: {{ $proto.port }}
      name: {{ $name }}
  {{-   end }}
  {{- end }}
{{- end }}
{{- $name := printf "server-%03d" $i }}
{{- $srv := deepCopy $server }}
{{- if hasKey $srv.configs $name }}
{{-   $srv := get $srv.configs $name | mergeOverwrite $srv }}
{{- end}}
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ $name }}
  namespace: {{ $ns }}
  labels:
    app: ort
    ort.olix0r.net/role: server
    ort.olix0r.net/instance: {{ quote $i }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ort
    ort.olix0r.net/role: server
    ort.olix0r.net/instance: {{ quote $i }}
  name: {{ $name }}
  namespace: {{ $ns }}
spec:
  selector:
    matchLabels:
      app: ort
      ort.olix0r.net/role: server
      ort.olix0r.net/instance: {{ quote $i }}
  replicas: {{ $replicas }}
  template:
    metadata:
      labels:
        app: ort
        ort.olix0r.net/role: server
        ort.olix0r.net/instance: {{ quote $i }}
      annotations:
{{ $linkerd | include "ort.linkerd" | indent 8 }}
    spec:
      serviceAccount: {{ $name }}
      containers:
        - name: main
          image: {{ $img }}
          env:
            - name: RUST_LOG
              value: {{ $srv.log | default "info" | quote }}
          {{- if eq $linkerd.inject "disabled" }}
            - name: LINKERD_DISABLED
              value: "true"
          {{- end }}
          args:
          {{- if $srv.threads }}
            - --threads={{ $srv.threads }}
          {{- end }}
            - server
          {{- range $f, $v := $srv.flags }}
            - --{{ kebabcase $f }}={{ $v }}
          {{- end }}
          ports:
          {{- range $name, $config := $protocols }}
          {{-   if $config }}
            - protocol: TCP
              containerPort: {{ $config.port }}
              name: {{ $name }}
          {{-   end }}
          {{- end }}
{{- end}}
