{{- $ns := .Release.Namespace }}
{{- $img := .Values.image }}
{{- $replicas := int .Values.server.replicas }}
{{- $server := .Values.server }}
{{- $linkerd := deepCopy .Values.linkerd | merge $server.linkerd }}
{{- $protocols := .Values.protocols }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ort
  name: server
  namespace: {{$ns}}
spec:
  selector:
    app: ort
    ort.olix0r.net/role: server
  ports:
  {{- range $name, $proto := $protocols }}
  {{-   if $proto }}
    - port: {{ $proto.port }}
      targetPort: {{ $proto.port }}
      name: {{ $name }}
  {{-   end }}
  {{- end }}
{{- if eq $linkerd.inject "enabled" }}
---
apiVersion: split.smi-spec.io/v1alpha1
kind: TrafficSplit
metadata:
  namespace: {{ $ns }}
  name: server
spec:
  service: server
  backends:
  {{- range $i, $e := until (.Values.server.services | int) }}
    - service: server-{{ printf "%03d" $i }}
      weight: 1
  {{- end }}
{{- end}}
{{- range $i, $e := until (.Values.server.services | int) }}
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: server-{{printf "%03d" $i}}
  namespace: {{ $ns }}
  labels:
    app: ort
    ort.olix0r.net/role: server
    ort.olix0r.net/instance: {{quote $i}}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ort
  name: server-{{printf "%03d" $i}}
  namespace: {{$ns}}
spec:
  selector:
    app: ort
    ort.olix0r.net/role: server
    ort.olix0r.net/instance: {{quote $i}}
  ports:
  {{- range $name, $proto := $protocols }}
  {{-   if $proto }}
    - port: {{ $proto.port }}
      targetPort: {{ $proto.port }}
      name: {{ $name }}
  {{-   end }}
  {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ort
    ort.olix0r.net/role: server
    ort.olix0r.net/instance: {{quote $i}}
  name: server-{{printf "%03d" $i}}
  namespace: {{$ns}}
spec:
  selector:
    matchLabels:
      app: ort
      ort.olix0r.net/role: server
      ort.olix0r.net/instance: {{quote $i}}
  replicas: {{$replicas}}
  template:
    metadata:
      labels:
        app: ort
        ort.olix0r.net/role: server
        ort.olix0r.net/instance: {{quote $i}}
      annotations:
{{ $linkerd | include "ort.linkerd" | indent 8 }}
    spec:
      serviceAccount: server-{{printf "%03d" $i}}
      containers:
        - name: main
          image: {{$img}}
          env:
            - name: RUST_LOG
              value: {{ $server.log | default "info" | quote }}
          {{- if eq $linkerd.inject "disabled" }}
            - name: LINKERD_DISABLED
              value: "true"
          {{- end }}
          args:
          {{- if $server.threads }}
            - --threads={{ $server.threads }}
          {{- end }}
            - server
          ports:
          {{- range $name, $config := $protocols }}
          {{-   if $config }}
            - protocol: TCP
              containerPort: {{ $config.port }}
              name: {{ $name }}
          {{-   end }}
          {{- end }}
{{- end}}
